version: '3.3'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    expose:
      - "3306"
      - "33006"
  app:
    build: .
    restart: always
    ports:
      - "9300:8080"
    volumes:
      - ./uploads:/uploads